version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/public
      - ./config.php:/var/www/config.php
    working_dir: /var/www
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
